namespace ScumRconTool.ViewModels;

public sealed class UiTextProvider : ObservableObject
{
    private readonly Dictionary<string, (string De, string En)> _texts = new(StringComparer.OrdinalIgnoreCase)
    {
        ["SwitchLanguage"] = ("\U0001F1EC\U0001F1E7 English", "\U0001F1E9\U0001F1EA Deutsch"),
        ["CheckUpdate"] = ("Update pruefen", "Check update"),
        ["DownloadUpdate"] = ("Update herunterladen", "Download update"),
        ["OpenDownload"] = ("Download oeffnen", "Open download"),
        ["GgconDocs"] = ("ggCON Doku", "ggCON docs"),
        ["UsageDirectoryOptIn"] = ("SCUM-Server freiwillig in der öffentlichen LMNT Serverliste anzeigen", "Voluntarily show this SCUM server in the public LMNT server directory"),
        ["UsageDirectoryDescription"] = ("Übertragen werden Servername, öffentliche SCUM-Server-IP, Tool-Version, letzter Meldezeitpunkt und eine technische Installationskennung. Keine Passwörter, Logs, Spieler-IDs, Chat- oder Scriptinhalte.", "Server name, public SCUM server IP, tool version, latest report time, and a technical installation identifier are transmitted. No passwords, logs, player IDs, chat data, or script contents."),
        ["UsageDirectoryOpenSource"] = ("Open Source auf GitHub ansehen", "Review the open-source project on GitHub"),
        ["UsageDirectoryApi"] = ("LMNT Serverlisten-API (HTTPS)", "LMNT server-directory API (HTTPS)"),
        ["UsageDirectoryStatusEnabled"] = ("LMNT Serverliste: freiwillig freigegeben; Aktualisierung alle 15 Minuten.", "LMNT server directory: voluntarily enabled; updated every 15 minutes."),
        ["UsageDirectoryStatusDisabled"] = ("LMNT Serverliste: nicht freigegeben.", "LMNT server directory: not enabled."),
        ["Status"] = ("Status", "Status"),
        ["CurrentPlayers"] = ("Aktuelle Spieler", "Current players"),
        ["Dashboard"] = ("Dashboard", "Dashboard"),
        ["Scripts"] = ("Skripte", "Scripts"),
        ["ScriptZone"] = ("Skriptzone", "Script zone"),
        ["RconConsole"] = ("RCON Console", "RCON console"),
        ["DiscordBridge"] = ("Discord Bridge", "Discord bridge"),
        ["ChatCommands"] = ("Chat Commands", "Chat commands"),
        ["RedeemCodes"] = ("RedeemCodes", "Redeem codes"),
        ["JoinCommands"] = ("Join Commands", "Join commands"),
        ["KillFeed"] = ("Kill Feed", "Kill feed"),
        ["WeeklyTasks"] = ("Weekly Tasks", "Weekly tasks"),
        ["RewardMode"] = ("Reward-Typ", "Reward type"),
        ["RewardDistribution"] = ("Auszahlung", "Distribution"),
        ["GoalScope"] = ("Zielmodus", "Goal mode"),
        ["RewardItems"] = ("Reward-Items", "Reward items"),
        ["AddRewardItem"] = ("+ Item", "+ item"),
        ["RewardItem"] = ("Item-Klassenname", "Item class name"),
        ["RewardQuantity"] = ("Item-Anzahl", "Item quantity"),
        ["RewardStackCount"] = ("StackCount (optional)", "Stack count (optional)"),
        ["RewardMoney"] = ("Geld pro Empfaenger", "Money per recipient"),
        ["WeeklySquads"] = ("Squads und Spieler", "Squads and players"),
        ["WeeklyRewardList"] = ("Reward-Empfaenger und Auszahlungen", "Reward recipients and payouts"),
        ["AcknowledgeReward"] = ("Quittieren", "Acknowledge"),
        ["WeeklyRewardHelp"] = ("Pro Teilnehmer: jedes Mitglied eines erfolgreichen Squads. Pro Squad: einmal an das ranghoechste Squad-Mitglied.", "Per participant: every member of a successful squad. Per squad: once to the highest-ranking squad member."),
        ["AutoMessages"] = ("Auto Messages", "Auto messages"),
        ["DebugLogs"] = ("Debug Logs", "Debug logs"),
        ["Settings"] = ("Settings", "Settings"),
        ["OpenFolder"] = ("Ordner", "Folder"),
        ["Clear"] = ("Leeren", "Clear"),
        ["Connect"] = ("Verbinden", "Connect"),
        ["Send"] = ("Senden", "Send"),
        ["StartDiscord"] = ("Discord starten", "Start Discord"),
        ["UpdateServerStatus"] = ("Serverstatus-Nachricht aktualisieren", "Update server status message"),
        ["StartChatLogAuto"] = ("Chatlog Auto starten", "Start chatlog auto"),
        ["StopChatLogAuto"] = ("Chatlog Auto stoppen", "Stop chatlog auto"),
        ["SendChatLogEmbedsNow"] = ("Chatlog jetzt als Embeds senden", "Send chatlog embeds now"),
        ["SaveSettings"] = ("Einstellungen speichern", "Save settings"),
        ["Start"] = ("Start", "Start"),
        ["Stop"] = ("Stop", "Stop"),
        ["ScanNow"] = ("Scan jetzt", "Scan now"),
        ["AddCommand"] = ("+ Befehl", "+ Command"),
        ["RemoveCommand"] = ("- Befehl", "- Command"),
        ["InsertExamples"] = ("Beispiele einfuegen", "Insert examples"),
        ["InsertExample"] = ("Beispiel einfuegen", "Insert example"),
        ["Save"] = ("Speichern", "Save"),
        ["DoNotSave"] = ("Nicht speichern", "Don't save"),
        ["Cancel"] = ("Abbrechen", "Cancel"),
        ["Delete"] = ("Loeschen", "Delete"),
        ["RemoveDelete"] = ("- Loeschen", "- Delete"),
        ["ExecuteForAllOnlinePlayers"] = ("Fuer alle Online-Spieler ausfuehren", "Run for all online players"),
        ["ScanDiscordNow"] = ("Scan + Discord jetzt", "Scan + Discord now"),
        ["ResetBaseline"] = ("Startwert neu setzen", "Reset baseline"),
        ["JsonResetExample"] = ("JSON Reset Beispiel", "JSON reset example"),
        ["NewChallenge"] = ("Neue Challenge", "New challenge"),
        ["ReloadExistingData"] = ("Aus vorhandenen Daten neu laden", "Reload from existing data"),
        ["SaveAllChallenges"] = ("Alle Challenges speichern", "Save all challenges"),
        ["Duplicate"] = ("Duplizieren", "Duplicate"),
        ["SendNow"] = ("Jetzt senden", "Send now"),
        ["ResetQueue"] = ("Queue auf Anfang", "Reset queue"),
        ["AddMessage"] = ("+ Nachricht", "+ Message"),
        ["AddCode"] = ("Code hinzufuegen", "Add code"),
        ["Reload"] = ("Neu laden", "Reload"),
        ["CreateNew"] = ("+ Neu", "+ New"),
        ["Refresh"] = ("Aktualisieren", "Refresh"),
        ["ValidateJson"] = ("JSON validieren", "Validate JSON"),
        ["FormatJson"] = ("JSON formatieren", "Format JSON"),
        ["AddSpawn"] = ("+ Spawn", "+ Spawn"),
        ["RemoveSpawn"] = ("- Spawn", "- Spawn"),
        ["AddLootPack"] = ("+ LootPack", "+ Loot pack"),
        ["RemoveLootPack"] = ("- LootPack", "- Loot pack"),
        ["AddItem"] = ("+ Item", "+ Item"),
        ["RemoveItem"] = ("- Item", "- Item"),
        ["RemoveLootCommand"] = ("- Loot Command", "- Loot command"),
        ["AddLootCommand"] = ("+ Loot Cmd", "+ Loot Cmd"),
        ["AddLiveCommand"] = ("+ Live Cmd", "+ Live Cmd"),
        ["AddLootCoordinate"] = ("+ Loot Koordinate", "+ Loot coordinate"),
        ["AddNpcCoordinate"] = ("+ NPC Koordinate", "+ NPC coordinate"),
        ["PasteCoords"] = ("Coords einfuegen", "Paste coords"),
        ["PasteCoordsTooltip"] = ("SCUM-Koordinaten aus der Zwischenablage in X/Y/Z uebernehmen.", "Paste SCUM coordinates from the clipboard into X/Y/Z."),
        ["Remove"] = ("- Entfernen", "- Remove"),
        ["RemovePack"] = ("- Pack", "- Pack"),
        ["AddNpcLootCommandPack"] = ("+ NPC/Loot CommandPack", "+ NPC/Loot command pack"),
        ["OpenLogFolder"] = ("Log-Ordner oeffnen", "Open log folder"),
        ["ClearLogDisplayAndFile"] = ("Anzeige + Datei leeren", "Clear view + file"),
        ["ServiceRunning"] = ("Dienst aktiv: {0}", "Service running: {0}"),
        ["ServiceActive"] = ("Dienst aktiv", "Service active"),
        ["AutoStart"] = ("Automatisch starten", "Start automatically"),
        ["Command"] = ("Command", "Command"),
        ["Response"] = ("Antwort", "Response"),
        ["Delay"] = ("Delay", "Delay"),
        ["Seconds"] = ("Sekunden", "seconds"),
        ["CodeInChat"] = ("Code im Chat", "Code in chat"),
        ["MaxUses"] = ("Max. Nutzungen", "Max uses"),
        ["AlreadyUsed"] = ("Bereits genutzt", "Already used"),
        ["UnlimitedHint"] = ("0 = unbegrenzt", "0 = unlimited"),
        ["ExecuteAsRedeemingPlayer"] = ("Als ExecAs fuer einloesenden Spieler ausfuehren", "Run as ExecAs for redeeming player"),
        ["RedeemDescription"] = ("Spieler loesen einen Code ein, indem sie ihn exakt in den Ingame-Chat schreiben, z.B. /starter. Das Tool liest denselben Chatlog wie Chat Commands und fuehrt dann den hinterlegten RCON-Command aus. Mit ExecAs wird automatisch die SteamID des einloesenden Spielers eingesetzt, also wird aus #SpawnItem Weapon_SKS 1 ein #ExecAs <SteamID> #SpawnItem Weapon_SKS 1.", "Players redeem a code by typing it exactly into in-game chat, for example /starter. The tool reads the same chat log as Chat Commands and then runs the configured RCON command. With ExecAs, the redeeming player's SteamID is inserted automatically, so #SpawnItem Weapon_SKS 1 becomes #ExecAs <SteamID> #SpawnItem Weapon_SKS 1."),
        ["RedeemAutoStart"] = ("RedeemCodes/Chat Commands automatisch starten", "Start Redeem Codes/Chat Commands automatically"),
        ["RedeemSharedSourceHint"] = ("RedeemCodes nutzen dieselbe Chatlog-Quelle wie Chat Commands. Quelle, Poll und Backfill stellst du zentral unter Settings ein.", "Redeem Codes use the same chat-log source as Chat Commands. Configure source, poll interval, and backfill centrally under Settings."),
        ["RedeemMaxUsesHint"] = ("Max. Nutzungen: 1 bedeutet einmalig fuer alle Spieler, 0 bedeutet unbegrenzt. Der Nutzungszaehler wird nach erfolgreichem Command oder erfolgreicher Antwort gespeichert. Platzhalter in Command und Antwort: {name}, {playerName}, {steamId}, {message}, {rawLine}.", "Max uses: 1 means one-time use across all players, 0 means unlimited. The usage counter is saved after a successful command or response. Placeholders in command and response: {name}, {playerName}, {steamId}, {message}, {rawLine}."),
        ["ChatCommandsDescription"] = ("Liest den SCUM-Chat aus ggCON HTTP Logs oder SFTP und fuehrt passende Regeln per RCON aus. Commands werden in Global, Local, Squad und Admin Chat erkannt. Die Regeln werden unten als einzelne, aufklappbare Commands gepflegt; kein rohes JSON mehr noetig. Die Command-Felder haben SCUM-Autovervollstaendigung. Mit ExecAs wird die SteamID des Chat-Spielers automatisch eingefuegt.", "Reads SCUM chat from ggCON HTTP logs or SFTP and runs matching rules through RCON. Commands are detected in Global, Local, Squad, and Admin chat. Rules are edited below as individual expandable commands; raw JSON is no longer required. Command fields provide SCUM autocomplete. ExecAs inserts the chat player's SteamID automatically."),
        ["ChatSharedSourceHint"] = ("Chat Commands und RedeemCodes nutzen dieselbe zentrale Chatlog-Quelle. ggCON HTTP/SFTP, Poll und Backfill stellst du unter Settings ein.", "Chat Commands and Redeem Codes use the same central chat-log source. Configure ggCON HTTP/SFTP, poll interval, and backfill under Settings."),
        ["ChatAutoStart"] = ("Chat Commands automatisch starten", "Start Chat Commands automatically"),
        ["WelcomeNewPlayers"] = ("Neue Spieler automatisch einmalig begruessen", "Welcome new players once automatically"),
        ["WelcomeType"] = ("Welcome Typ", "Welcome type"),
        ["WelcomeMessage"] = ("Welcome Nachricht", "Welcome message"),
        ["WelcomeHint"] = ("Wird per #MessagePlayer beim ersten erkannten Chat einer SteamID gesendet. Platzhalter: {name}, {steamId}, {message}, {rawLine}.", "Sent via #MessagePlayer when a SteamID is seen in chat for the first time. Placeholders: {name}, {steamId}, {message}, {rawLine}."),
        ["PaidVotes"] = ("Votes mit Ingamegeld kaufen", "Buy votes with in-game money"),
        ["VotePrice"] = ("Vote-Kaufpreis", "Vote price"),
        ["Confirmation"] = ("Bestaetigung", "Confirmation"),
        ["VotePrompt"] = ("Vote Kauf-Anfrage", "Vote purchase prompt"),
        ["VoteInsufficientFunds"] = ("Vote Nicht-genug-Geld-Antwort", "Vote insufficient-funds response"),
        ["Commands"] = ("Commands", "Commands"),
        ["ChatCommandsHelp"] = ("Pro Eintrag: Trigger setzen, Match-Art waehlen, optional Delay in Sekunden, Command und/oder Antwort eintragen. /wc ruft den aktuellen Challenge-Status ab. /buyevent zeigt kaufbare Buyzone-Events, /buyevent Name kauft und aktiviert privat fuer den Spieler. Platzhalter: {name}, {playerName}, {steamId}, {message}, {rawLine}, {challenges}, {challengeStatus}, {randomEvents}, {randomEventsCount}, {randomEventsLive}, {randomEventsInitiated}, {randomEventsCleanup}.", "Per entry: set the trigger, choose the match mode, optionally set a delay in seconds, then enter a command and/or response. /wc returns the current challenge status. /buyevent lists buyable Buyzone events; /buyevent Name buys and activates one privately for the player. Placeholders: {name}, {playerName}, {steamId}, {message}, {rawLine}, {challenges}, {challengeStatus}, {randomEvents}, {randomEventsCount}, {randomEventsLive}, {randomEventsInitiated}, {randomEventsCleanup}."),
        ["Trigger"] = ("Trigger", "Trigger"),
        ["Match"] = ("Match", "Match"),
        ["Cooldown"] = ("Cooldown", "Cooldown"),
        ["Scope"] = ("Scope", "Scope"),
        ["GlobalAntiSpamCooldown"] = ("Globaler Anti-Spam Cooldown", "Global anti-spam cooldown"),
        ["RunAsExecAs"] = ("Als ExecAs ausfuehren", "Run as ExecAs"),
        ["ScriptBoardPlan"] = ("Bausteinplan", "Flow builder"),
        ["GlobalLootPacks"] = ("Globale Lootpacks", "Global loot packs"),
        ["ScumMap"] = ("SCUM Karte", "SCUM map"),
        ["CoordinatesAndVariables"] = ("Koordinaten & Variablen", "Coordinates & variables"),
        ["NpcPoints"] = ("NPC-Punkte", "NPC points"),
        ["LootPoints"] = ("Loot-Punkte", "Loot points"),
        ["AddNpcPoint"] = ("NPC-Punkt hinzufuegen", "Add NPC point"),
        ["AddLootPoint"] = ("Loot-Punkt hinzufuegen", "Add loot point"),
        ["PointsHelp"] = ("Punkte sind nur gespeicherte Orte. Spawns, CargoDrops und Lootpacks waehlen spaeter einen dieser Punkte aus.", "Points are saved locations only. Spawns, cargo drops, and loot packs select one of these points later."),
        ["NpcPointsHelp"] = ("Orte, an denen Spawn-Bausteine erscheinen koennen.", "Locations where spawn blocks can appear."),
        ["LootPointsHelp"] = ("Orte, an denen ausgewaehlte Lootpacks gespawnt werden.", "Locations where selected loot packs are spawned."),
        ["Name"] = ("Name", "Name"),
        ["EventStart"] = ("Event Start", "Event start"),
        ["TriggerZone"] = ("Triggerzone", "Trigger zone"),
        ["Initiation"] = ("Initiierung", "Initiation"),
        ["NpcSpawns"] = ("Spawn-Bausteine", "Spawn blocks"),
        ["LootPacks"] = ("Lootpacks", "Loot packs"),
        ["GgconHttpApiLogs"] = ("ggCON HTTP API & Logs", "ggCON HTTP API & logs"),
        ["GgconSettingsHint"] = ("Diese Einstellungen gelten zentral fuer Module, die ggCON HTTP GETs nutzen: Chat Commands, RedeemCodes, Wetter/Status und Vote-Kontoabfragen.", "These settings apply centrally to modules that use ggCON HTTP GETs: Chat Commands, Redeem Codes, weather/status, and vote account lookups."),
        ["BaseUrlOptional"] = ("Base URL optional, leer = http://Host:HTTP-Port", "Base URL optional, blank = http://Host:HTTP port"),
        ["HttpPortHint"] = ("HTTP Port, bei GGHost meist RCON-Port minus 1, z.B. 5376", "HTTP port, usually RCON port minus 1 on GGHost, e.g. 5376"),
        ["HttpPasswordHint"] = ("HTTP Passwort optional, leer = RCON Passwort", "HTTP password optional, blank = RCON password"),
        ["UseGgconHttpLogs"] = ("ggCON HTTP Logs fuer Chat Commands und RedeemCodes nutzen", "Use ggCON HTTP logs for Chat Commands and Redeem Codes"),
        ["LogPollSeconds"] = ("Log Poll Sekunden", "Log poll seconds"),
        ["InitialBackfillSeconds"] = ("Initial Backfill Sekunden", "Initial backfill seconds"),
        ["DiscordGgconCentralHint"] = ("ggCON HTTP API, Log-Quelle, Poll und Backfill werden zentral unter Settings gepflegt.", "ggCON HTTP API, log source, poll interval, and backfill are managed centrally under Settings."),
        ["SourceRconConnection"] = ("Source-RCON Verbindung", "Source RCON connection"),
        ["IngameChatCommandsShort"] = ("Ingame-Chat Befehle", "In-game chat commands"),
        ["LoginDelayCommandsShort"] = ("Loginlog Delay-Befehle", "Login-log delayed commands"),
        ["JsonEventFiles"] = ("JSON Event-Dateien", "JSON event files"),
        ["ScriptStatus"] = ("Script Status", "Script status"),
        ["ScriptStatusHint"] = ("Blau = initialisiert/scharf, Gruen = gestartet/live.", "Blue = initiated/armed, green = started/live."),
        ["LastActions"] = ("Letzte Aktionen", "Latest actions"),
        ["RconConsoleDescription"] = ("Befehle werden an ggCON per Source-RCON gesendet. Antworten sind in der Regel JSON.", "Commands are sent to ggCON through Source RCON. Responses are usually JSON."),
        ["DiscordBotDescription"] = ("Der Bot liest nur den angegebenen Bridge-Channel und baut daraus sichere Broadcasts. Nachrichten mit #, /, !, ., ; oder $ am Anfang werden blockiert.", "The bot reads only the configured bridge channel and turns messages into safe broadcasts. Messages starting with #, /, !, ., ;, or $ are blocked."),
        ["ServerStatusChannelId"] = ("Serverstatus Nachricht Channel-ID", "Server status message channel ID"),
        ["ServerStatusAutoUpdate"] = ("Serverstatus als eine Nachricht automatisch aktualisieren", "Auto-update server status as one message"),
        ["DiscordBotStatusUpdate"] = ("Discord Botstatus mit Spieleranzahl aktualisieren", "Update Discord bot status with player count"),
        ["ServerStatusTitle"] = ("Serverstatus Titel", "Server status title"),
        ["ServerName"] = ("Servername", "Server name"),
        ["ServerAddressHint"] = ("Server-IP / Adresse fuer Discord, leer = Host:GamePort", "Server IP/address for Discord, blank = Host:GamePort"),
        ["CheckUpdatesOnStart"] = ("Updates beim Start pruefen", "Check for updates on startup"),
        ["DiscordIngameEnable"] = ("Discord -> Ingame aktivieren", "Enable Discord -> in-game"),
        ["ChatlogEmbedsEnable"] = ("Chatlogs als Embed aktivieren", "Enable chat logs as embeds"),
        ["VehicleLogEmbedsEnable"] = ("Vehicle-Destruction Logs als Embed aktivieren", "Enable vehicle-destruction logs as embeds"),
        ["ChatlogsAutoStart"] = ("Chatlogs automatisch starten", "Start chat logs automatically"),
        ["GameBridgeMessageType"] = ("Message Type fuer Ingame-Broadcast", "Message type for in-game broadcast"),
        ["JoinDescription"] = ("Liest den SCUM-Loginlog per SFTP und plant nach einem Join verzoegerte RCON-Befehle. Die Regeln werden unten als einzelne Commands gepflegt; kein rohes JSON mehr noetig. Die Command-Felder haben SCUM-Autovervollstaendigung. Mit ExecAs wird die SteamID des joinenden Spielers automatisch eingefuegt.", "Reads the SCUM login log through SFTP and schedules delayed RCON commands after a player joins. Rules are edited below as individual commands; raw JSON is no longer required. Command fields provide SCUM autocomplete. ExecAs inserts the joining player's SteamID automatically."),
        ["JoinAutoStart"] = ("Join Commands automatisch starten", "Start Join Commands automatically"),
        ["JoinCommandsHelp"] = ("Pro Eintrag: aktivieren, Delay in Sekunden setzen, Command eintippen oder aus der Vorschlagsliste waehlen und optional als ExecAs fuer den joinenden Spieler ausfuehren. Eine optionale Ziel-SteamID beschraenkt die Regel auf diesen Spieler. \"Nur einmal pro Join\" meint dieselbe erkannte Login-Zeile; bei einem spaeteren Rejoin kann der Command wieder laufen. Platzhalter bleiben moeglich: {name}, {playerName}, {steamId}, {rawLine}.", "Per entry: enable it, set the delay in seconds, type a command or choose one from suggestions, and optionally run it as ExecAs for the joining player. An optional target SteamID limits the rule to that player. \"Only once per join\" means the same detected login line; after a later rejoin the command can run again. Placeholders remain available: {name}, {playerName}, {steamId}, {rawLine}."),
        ["DelaySeconds"] = ("Delay Sekunden", "Delay seconds"),
        ["TargetSteamId"] = ("Nur SteamID", "Only SteamID"),
        ["TargetSteamIdTooltip"] = ("Leer lassen = alle Spieler. Mehrere IDs mit Komma oder Leerzeichen trennen.", "Leave blank = all players. Separate multiple IDs with commas or spaces."),
        ["OnlyOncePerJoin"] = ("Nur einmal pro Join ausfuehren", "Run only once per join"),
        ["OnlyOncePerJoinTooltip"] = ("Verhindert doppelte Ausfuehrung fuer dieselbe erkannte Login-Zeile. Wenn der Spieler spaeter neu joined, kann der Command wieder geplant werden.", "Prevents duplicate execution for the same detected login line. If the player joins again later, the command can be scheduled again."),
        ["KillFeedDescription"] = ("Laedt die neueste Killlog-Datei per SFTP, merkt bereits bekannte Kill-Zeilen und sendet neue Kills als #Broadcast mit einstellbarer Farbe in den Ingamechat. Beim allerersten Lauf werden vorhandene Zeilen nur gemerkt, damit alte Kills nicht gespammt werden.", "Loads the newest kill-log file through SFTP, remembers known kill lines, and sends new kills as #Broadcast messages with a configurable color. On the first run existing lines are remembered only, so old kills are not spammed."),
        ["KillFeedAutoStart"] = ("Killfeed automatisch starten", "Start kill feed automatically"),
        ["PollSeconds"] = ("Poll Sekunden", "Poll seconds"),
        ["IngameMessageColor"] = ("Ingame Nachricht Farbe", "In-game message color"),
        ["IngameMessageTemplate"] = ("Ingame Nachricht Template", "In-game message template"),
        ["WeeklyProgressTitle"] = ("Community Fortschritt aus scum.db", "Community progress from scum.db"),
        ["WeeklyDescription"] = ("Laedt die scum.db per SFTP, speichert beim Start einen Basiswert und berechnet danach nur die Differenz. Discord wird alle 30 Minuten aktualisiert, aber nur wenn Spieler online sind.", "Loads scum.db through SFTP, stores a baseline on start, and then calculates only the difference. Discord is updated every 30 minutes, but only when players are online."),
        ["WeeklyAutoStart"] = ("Weekly Tasks automatisch starten", "Start Weekly Tasks automatically"),
        ["OnlyWhenPlayersOnline"] = ("Nur bei Spielern online", "Only when players are online"),
        ["WeeklyOnlyWhenPlayersOnline"] = ("DB nur aktualisieren, wenn Spieler online sind", "Update DB only when players are online"),
        ["WeeklyDbPath"] = ("SCUM.db Remote-Dateipfad absolut", "Absolute SCUM.db remote file path"),
        ["WeeklyDiscordChannelHint"] = ("Discord Channel-ID fuer Weekly Tasks (leer/0 = Serverstatus Channel)", "Discord channel ID for Weekly Tasks (blank/0 = server status channel)"),
        ["UpdateIntervalMinutes"] = ("Update Intervall Minuten", "Update interval minutes"),
        ["ChallengePlanner"] = ("Challenge-Planer", "Challenge planner"),
        ["ChallengePlannerDescription"] = ("Jede Challenge ist eine eigene Card. Neue Challenges werden als neue Card angelegt, bestehende werden nicht ueberschrieben. Geplante Tasks starten ab Startzeit; abgelaufene Tasks werden nicht mehr aktualisiert/angezeigt.", "Each challenge is its own card. New challenges are added as new cards; existing ones are not overwritten. Scheduled tasks start at their start time; expired tasks are no longer updated/shown."),
        ["Enabled"] = ("Aktiv", "Enabled"),
        ["EnabledFull"] = ("Aktiviert", "Enabled"),
        ["UniqueId"] = ("ID eindeutig", "Unique ID"),
        ["Type"] = ("Typ", "Type"),
        ["Title"] = ("Titel", "Title"),
        ["TargetValue"] = ("Zielwert", "Target value"),
        ["TargetFromScumDb"] = ("Ziel aus SCUM.db", "Target from SCUM.db"),
        ["StartTimeLocalOptional"] = ("Startzeit lokal, optional: yyyy-MM-dd HH:mm", "Local start time, optional: yyyy-MM-dd HH:mm"),
        ["DurationHours"] = ("Laufzeit Stunden", "Duration hours"),
        ["MinimumParticipationPercent"] = ("Mindestbeteiligung Prozent", "Minimum participation percent"),
        ["Planning"] = ("Planung", "Schedule"),
        ["Description"] = ("Beschreibung", "Description"),
        ["Mode"] = ("Modus", "Mode"),
        ["Color"] = ("Farbe", "Color"),
        ["Minutes"] = ("Minuten", "minutes"),
        ["TextLabel"] = ("Text", "Text"),
        ["QueueMinutes"] = ("Queue Minuten", "Queue minutes"),
        ["MaxLength"] = ("Max. Laenge", "Max length"),
        ["FallbackNoChallenge"] = ("Fallback bei keiner Challenge", "Fallback when no challenge is active"),
        ["ScriptZoneDescription"] = ("Ablaufbloecke statt Roh-JSON. JSON bleibt im Hintergrund kompatibel.", "Flow blocks instead of raw JSON. JSON remains compatible in the background."),
        ["EngineRunning"] = ("Engine laeuft", "Engine running"),
        ["RandomEventScheduler"] = ("Random Event Scheduler", "Random event scheduler"),
        ["StartAfterRestartSchedule"] = ("Nach Restart-Zeitplan starten", "Start after restart schedule"),
        ["RandomQuestIntervalLabel"] = ("Turnus bis zum naechsten Event (Minuten)", "Interval until the next event (minutes)"),
        ["RandomQuestStartDelayLabel"] = ("Startverzoegerung nach Restart (Minuten)", "Start delay after restart (minutes)"),
        ["RestartTimesLocal"] = ("Restart-Zeiten lokal", "Local restart times"),
        ["RandomSchedulerHint"] = ("Wenn der Zeitplan aus ist, nutzt jedes Script seinen eigenen Randomizer-Minutenwert.", "When the schedule is off, each script uses its own randomizer minute value."),
        ["ActivationZone"] = ("Aktivierungszone", "Activation zone"),
        ["Price"] = ("Preis", "Price"),
        ["ActivationChancePercent"] = ("Aktivierungs-Chance %", "Activation chance %"),
        ["RandomActivationTooltip"] = ("Nur fuer RandomActivated, 0-100 Prozent", "Only for RandomActivated, 0-100 percent"),
        ["BuyAliasTooltip"] = ("/buyevent Alias, leer = Name", "/buyevent alias, blank = name"),
        ["TimerMs"] = ("Timer ms", "Timer ms"),
        ["ServerMessage"] = ("Servernachricht", "Server message"),
        ["OptionalLoot"] = ("Optional Loot", "Optional loot"),
        ["SpawnMode"] = ("Spawnmodus", "Spawn mode"),
        ["EventStartDescription"] = ("Ablauf: Initiierung ist die Vorphase. Das Betreten der Triggerzone startet den Live-Teil, also Servernachricht, Spawns und Loot. Bei Buyzone oder DirectLive kann der Live-Teil sofort starten.", "Flow: initiation is the preparation phase. Entering the trigger zone starts the live phase: server message, spawns, and loot. With Buyzone or DirectLive, the live phase can start immediately."),
        ["TriggerZoneDescription"] = ("Diese Zone ist der Ausloeser. Wenn ein Spieler den Bereich betritt, geht das Event in den Live-Teil, sofern Modus und Cooldown es erlauben.", "This zone is the trigger. When a player enters the area, the event moves into the live phase if mode and cooldown allow it."),
        ["InitiationHelp"] = ("Nein: Initiierung ist nicht das Betreten der Zone. Sie ist die Vorbereitung davor, z. B. Random-Event ankuendigen oder Commands vor dem eigentlichen Start senden. Zone betreten startet danach Live.", "No: initiation is not entering the zone. It is the preparation before that, for example announcing a random event or sending commands before the actual start. Entering the zone then starts live."),
        ["AddNpcSpawn"] = ("Spawn hinzufuegen", "Add spawn"),
        ["NpcSpawnDescription"] = ("Ein Spawn-Baustein beschreibt, was erzeugt wird. Normale Typen bauen #Spawn automatisch; Custom ist ein freier Command, CargoDrop baut den WorldEvent-Command.", "A spawn block describes what is created. Normal types build #Spawn automatically; Custom is a free command, CargoDrop builds the world-event command."),
        ["WaitTimeMs"] = ("Wartezeit ms", "Wait time ms"),
        ["DespawnSeconds"] = ("Despawn Sek.", "Despawn sec."),
        ["CleanupEmptySeconds"] = ("Cleanup leer Sek.", "Cleanup empty sec."),
        ["ExecAsPlayer"] = ("ExecAs Spieler", "ExecAs player"),
        ["LootPacksDescription"] = ("Lootpacks sind Itemlisten. Der Spawnmodus entscheidet, ob ein Pack insgesamt oder je Loot-Punkt gespawnt wird.", "Loot packs are item lists. The spawn mode decides whether one pack is spawned in total or one per loot point."),
        ["CleanupDescription"] = ("Cleanup entfernt alte Eventreste, bevor oder nachdem ein Event laeuft. Der Button erzeugt Cleanup-Commands fuer alle Lootpunkte.", "Cleanup removes old event leftovers before or after an event runs. The button creates cleanup commands for all loot points."),
        ["CleanupAllLootPoints"] = ("Alle Lootpunkte bereinigen", "Clean up all loot points"),
        ["InitiatorMessage"] = ("Initiatornachricht", "Initiator message"),
        ["LootspawnCoordinateVariables"] = ("Lootspawn Koordinaten-Variablen", "Loot-spawn coordinate variables"),
        ["NpcspawnCoordinateVariables"] = ("NPCSpawn Koordinaten-Variablen", "NPC-spawn coordinate variables"),
        ["RawJson"] = ("Roh-JSON", "Raw JSON"),
        ["Flow"] = ("Ablauf", "Flow"),
        ["TitleMainSettings"] = ("Titel / Main Einstellungen", "Title / main settings"),
        ["ActivationZoneMap"] = ("Aktivierungszone / Karte", "Activation zone / map"),
        ["LiveblockSpawnBlocks"] = ("Liveblock - Spawn Bausteine", "Live block - spawn blocks"),
        ["AssetBlueprintTooltip"] = ("Asset oder Custom-Command je nach Typ", "Asset or custom command depending on type"),
        ["NoScriptSelected"] = ("Kein Script ausgewaehlt", "No script selected"),
        ["NoScriptSelectedSentence"] = ("Kein Script ausgewaehlt.", "No script selected."),
        ["MapLoading"] = ("Karte wird geladen...", "Loading map..."),
        ["MapNotLoaded"] = ("Karte nicht geladen.", "Map not loaded."),
        ["MapNotFound"] = ("Karte nicht gefunden: scum_kartographer/assets/scum_map.jpg", "Map not found: scum_kartographer/assets/scum_map.jpg"),
        ["MapLoadFailed"] = ("Karte konnte nicht geladen werden: {0}", "Map could not be loaded: {0}"),
        ["MapPointsCurrentScript"] = ("{0} Kartenpunkte aus dem aktuellen Script.", "{0} map points from the current script."),
        ["MapNotLoadedPointsRecognized"] = ("Karte nicht geladen. {0} Kartenpunkte erkannt.", "Map not loaded. {0} map points recognized."),
        ["MapHelp"] = ("Mausrad zoomt, linke Maustaste zieht die Karte. Ein Klick auf einen Eintrag zentriert den Punkt.", "Mouse wheel zooms, left mouse button pans the map. Click a list entry to center that point."),
        ["ZoomIn"] = ("Hereinzoomen", "Zoom in"),
        ["ZoomOut"] = ("Herauszoomen", "Zoom out"),
        ["NpcSpawnVariable"] = ("NPCSpawn Variable", "NPC spawn variable"),
        ["LootVariable"] = ("Loot Variable", "Loot variable"),
        ["SpawnBlockLabel"] = ("Spawn-Baustein", "Spawn block"),
        ["DebugDescription"] = ("Hier siehst du, was das Tool gerade macht: RCON-Verbindungen, gesendete Befehle, Discord-Bridge, Chatlog-Scans, Script-Engine und Fehler.", "This shows what the tool is doing right now: RCON connections, sent commands, Discord bridge, chat-log scans, script engine, and errors."),
        ["LogFile"] = ("Logdatei", "Log file"),
        ["LiveLog"] = ("Live Log", "Live log"),
        ["Password"] = ("Passwort", "Password"),
        ["SftpPassword"] = ("SFTP Passwort", "SFTP password"),
        ["ScriptsAutoStart"] = ("Scripts automatisch starten", "Start scripts automatically"),
        ["DiscordServerStatusAutoUpdate"] = ("Discord Serverstatus-Nachricht automatisch aktualisieren", "Auto-update Discord server status message"),
        ["DiscordBotStatusAutoUpdate"] = ("Discord Botstatus automatisch aktualisieren", "Auto-update Discord bot status"),
        ["VoteConfirmationSeconds"] = ("Vote-Bestaetigung Sekunden", "Vote confirmation seconds"),
        ["WeeklyPollMinutes"] = ("Weekly Poll Minuten", "Weekly poll minutes"),
        ["KillfeedPollSeconds"] = ("Killfeed Poll Sekunden", "Killfeed poll seconds"),
        ["ScriptPollSeconds"] = ("Script Poll Sekunden", "Script poll seconds"),
        ["RandomRestartTimesLocal"] = ("Random Restart-Zeiten lokal (z.B. 04:00,10:00,16:00,22:00)", "Local random restart times (e.g. 04:00,10:00,16:00,22:00)"),
        ["RandomQuestIntervalMinutes"] = ("Random Quest Intervall Minuten", "Random quest interval minutes"),
        ["RandomQuestStartDelayMinutes"] = ("Random Quest Startverzoegerung nach Restart Minuten", "Random quest start delay after restart minutes"),
        ["Weight"] = ("Gewicht", "Weight"),
        ["Quantity"] = ("Menge", "Quantity"),
        ["VariableName"] = ("Variablenname", "Variable name"),
        ["LootSelection"] = ("Loot Auswahl", "Loot selection"),
        ["Placeholder"] = ("Platzhalter", "Placeholders"),
        ["RewardText"] = ("Reward Text", "Reward text"),
        ["CompletedText"] = ("Completed Text", "Completed text"),
        ["ChatlogForwarderActive"] = ("Chatlog Forwarder aktiv", "Chat-log forwarder active"),
        ["BlockNameTooltip"] = ("Name des Bausteins", "Block name"),
        ["RconDelayTooltip"] = ("Delay nach dem RCON-Befehl in Millisekunden", "Delay after the RCON command in milliseconds"),
        ["DespawnLifetimeTooltip"] = ("DespawnLifetime in Sekunden, 0 = nicht anhaengen", "Despawn lifetime in seconds, 0 = do not append"),
        ["StartDelayMsTooltip"] = ("Startdelay in Millisekunden", "Start delay in milliseconds"),
        ["RepeatCountTooltip"] = ("Anzahl Spawn-Durchlaeufe", "Number of spawn passes"),
        ["RepeatEveryMsTooltip"] = ("Millisekunden zwischen Wiederholungen", "Milliseconds between repeats"),
        ["ExtraSpawnTooltip"] = ("Optionaler Zusatz, z. B. Modifier minimalfunctional", "Optional extra argument, e.g. modifier minimalfunctional"),
        ["ScriptEngineNotStarted"] = ("Script Engine nicht gestartet.", "Script engine not started."),
        ["ScriptRuntimeSummaryFormat"] = ("{0} initiiert, {1} gestartet/live, {2} cleanup, {3} cooldown.", "{0} initiated, {1} started/live, {2} cleanup, {3} cooldown."),
        ["ScriptNotValidated"] = ("Noch nicht validiert.", "Not validated yet."),
        ["ScriptUnsavedChanges"] = ("Ungespeicherte Aenderungen im geladenen Script.", "Unsaved changes in the loaded script."),
        ["ScriptViewSaved"] = ("Script-Ansicht ist gespeichert.", "Script view is saved."),
        ["WeeklyTasksNotStarted"] = ("Weekly Tasks nicht gestartet.", "Weekly Tasks not started."),
        ["AutoMessagesNotStarted"] = ("Auto Messages nicht gestartet.", "Auto Messages not started."),
        ["AutoMessagesRunningStatus"] = ("Auto Messages laufen: Queue alle {0} Minuten, Standalone nach eigenem Intervall.", "Auto Messages running: queue every {0} minutes, standalone by its own interval."),
        ["AutoMessagesStopped"] = ("Auto Messages gestoppt.", "Auto Messages stopped."),
        ["AutoMessageManualSent"] = ("Auto Message manuell gesendet/ausgefuehrt.", "Auto Message manually sent/executed."),
        ["AutoMessagesFlowReset"] = ("Auto Messages Flow auf Anfang gesetzt.", "Auto Messages flow reset to the beginning."),
        ["UpdateNotChecked"] = ("Update: noch nicht geprueft", "Update: not checked yet"),
        ["UpdateNoUrl"] = ("Update: keine Update-URL konfiguriert", "Update: no update URL configured"),
        ["UpdateChecking"] = ("Update: pruefe...", "Update: checking..."),
        ["UpdateInvalidResponse"] = ("Update: keine gueltige Antwort", "Update: no valid response"),
        ["UpdateCurrentFormat"] = ("Update: aktuell ({0})", "Update: current ({0})"),
        ["UpdateMandatoryAvailableFormat"] = ("Pflichtupdate verfuegbar: v{0}", "Mandatory update available: v{0}"),
        ["UpdateAvailableFormat"] = ("Update verfuegbar: v{0}", "Update available: v{0}"),
        ["UpdateCheckFailed"] = ("Update: Pruefung fehlgeschlagen", "Update: check failed"),
        ["DiscordStartedNotReady"] = ("Gestartet, nicht bereit", "Started, not ready"),
        ["DiscordNotReady"] = ("Nicht bereit", "Not ready"),
        ["JsonValid"] = ("JSON ist gueltig.", "JSON is valid."),
        ["JsonErrorFormat"] = ("JSON Fehler: {0}", "JSON error: {0}"),
        ["FormatFailedFormat"] = ("Formatieren fehlgeschlagen: {0}", "Formatting failed: {0}"),
        ["UnsavedScriptDialogTitle"] = ("Skriptzone - nicht gespeichert", "Script zone - not saved"),
        ["UnsavedScriptDialogText"] = ("Das aktuelle Skript hat ungespeicherte Aenderungen. Was soll passieren?", "The current script has unsaved changes. What should happen?"),
        ["NewCommand"] = ("Neuer Command", "New command"),
    };

    private string _language = "de";

    public UiTextProvider(string? language)
    {
        _language = Normalize(language);
    }

    public string Language => _language;
    public bool IsGerman => _language.Equals("de", StringComparison.OrdinalIgnoreCase);

    public string this[string key]
    {
        get
        {
            if (string.IsNullOrWhiteSpace(key)) return string.Empty;
            return _texts.TryGetValue(key, out var value)
                ? IsGerman ? value.De : value.En
                : key;
        }
    }

    public void SetLanguage(string? language)
    {
        var normalized = Normalize(language);
        if (_language.Equals(normalized, StringComparison.OrdinalIgnoreCase)) return;

        _language = normalized;
        OnPropertyChanged(nameof(Language));
        OnPropertyChanged(nameof(IsGerman));
        OnPropertyChanged("Item[]");
    }

    public void Toggle() => SetLanguage(IsGerman ? "en" : "de");

    private static string Normalize(string? language)
        => language?.StartsWith("en", StringComparison.OrdinalIgnoreCase) == true ? "en" : "de";
}
