<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\Services\ItemCatalogData.cs" Link="ItemCatalogData.cs" />
    <Content Include="..\..\dbs14756250.sql" Link="dbs14756250.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
