namespace ScumRconTool.Services;

public static class ScumCommandCatalog
{
    // Local offline suggestion catalog for the WPF command editors.
    // Keep only command signatures here, so selecting a suggestion inserts a directly editable command.
    public static IReadOnlyList<string> Commands { get; } = new[]
    {
        "#Announce <message>",
        "#Ban <SteamID64>",
        "#CancelVote",
        "#ChangeCurrencyBalance Normal <amount> <player|SteamID64>",
        "#ChangeCurrencyBalance Gold <amount> <player|SteamID64>",
        "#ChangeCurrencyBalanceToAll Normal <amount>",
        "#ChangeCurrencyBalanceToAll Gold <amount>",
        "#ChangeCurrencyBalanceToAllOnline Normal <amount>",
        "#ChangeCurrencyBalanceToAllOnline Gold <amount>",
        "#ChangeFamePoints <amount> <player|SteamID64>",
        "#CheckServerTime",
        "#ClearFakeName <player|SteamID64>",
        "#DestroyAllBaseBuildingElementsForFlag <flagID> please",
        "#DestroyAllBaseBuildingElementsForPlayer <steamID> please",
        "#DestroyAllBaseBuildingElementsForSquad <squadID> please",
        "#DestroyAllBaseBuildingWithinRadius <radius[m]> <location>",
        "#DestroyAllFlagsForPlayer <player|SteamID64>",
        "#DestroyAllItemsWithinRadius <item-name> <radius> <location>",
        "#DestroyAllRazorsWithinRadius <radius>",
        "#DestroyAllVehicles please",
        "#DestroyCorpsesWithinRadius <radius>",
        "#DestroyEncountersAtPlayerLocation",
        "#DestroyFlag <flagID>",
        "#DestroyVehicle <vehicleID>",
        "#DestroyZombiesWithinRadius <radius> <coordinates>",
        "#DumpAllSquadsInfoList",
        "#EndTournamentMode",
        "#ExecAs {steamId} #ShowNamePlates true",
        "#ExportCurrentLootTree",
        "#ExportDefaultItemSpawnerPresets",
        "#ExportDefaultItemSpawningCooldownGroups",
        "#ExportDefaultItemSpawningParameters",
        "#ExportDefaultLootTree",
        "#ExportItemSpawnerPresetsInZone <X1> <Y1> <X2> <Y2> <name>",
        "#FindSquadMember <SteamID64> true",
        "#ForceBBEncounterOnNearbyOwnedBase <SteamID64>",
        "#ForceDropshipEncounter <SteamID64>",
        "#GetSteamID <name>",
        "#GetSteamIDByRank <rank>",
        "#Kick <name|SteamID64>",
        "#ListActiveBunkers true",
        "#ListActiveHunts true",
        "#ListAnimals",
        "#ListFlags <page> true",
        "#ListItems",
        "#ListMutedPlayers true",
        "#ListPlayers true",
        "#ListSilencedPlayers true",
        "#ListSpawndAnimals true",
        "#ListSquadMembers <squadID> true",
        "#ListSquads <page> true",
        "#ListVehicles",
        "#ListZombies",
        "#Location <player|SteamID64>",
        "#MapTeleport <name|SteamID64>",
        "#Mute <name|SteamID64>",
        "#NightBrightness 1",
        "#PlayerInfo <SteamID64>",
        "#PrintGlobalRaidProtectionRaidTimes",
        "#RandomizePriceDeltas",
        "#ReloadCustomMapConfig",
        "#ReloadLootCustomizationsAndResetSpawners",
        "#RenameVehicle <vehicleID> <name>",
        "#ResetEconomy",
        "#ResetPlayerBalances <SteamID> please",
        "#ResetSquadInfo <squadID>",
        "#ScheduleCargoDrop",
        "#ScheduleWorldEvent BP_CargoDropEvent <location>",
        "#SetCurrencyBalance Normal <amount> <player|SteamID64>",
        "#SetCurrencyBalance Gold <amount> <player|SteamID64>",
        "#SetCurrencyBalanceToAll Normal <amount>",
        "#SetCurrencyBalanceToAll Gold <amount>",
        "#SetCurrencyBalanceToAllOnline Normal <amount>",
        "#SetCurrencyBalanceToAllOnline Gold <amount>",
        "#SetFakeName <fakeName> <player|SteamID64>",
        "#SetFamePoints <amount> <player|SteamID64>",
        "#SetFamePointsToAll <amount>",
        "#SetFamePointsToAllOnline <amount>",
        "#SetGodMode true",
        "#SetHealthToItemInHands 1",
        "#SetShouldPrintExamineSpawnerPresets true",
        "#SetTime <0-23>",
        "#SetWeather <0.1-1>",
        "#ShowAnimalLocation true",
        "#ShowArmedNPCsLocation true",
        "#ShowFlagInfo true",
        "#ShowFlagLocations true",
        "#ShowNamePlates true",
        "#ShowOtherPlayerInfo true",
        "#ShowOtherPlayerLocations true",
        "#ShowVehicleInfo true",
        "#ShowVehicleLocations true",
        "#ShowZombiesLocation true",
        "#ShutdownServer pretty please",
        "#Silence <name|SteamID64>",
        "#SpawnAnimal <animal> <amount> <position>",
        "#SpawnInventoryFullOf <inventoryName> <itemCount> <itemName>",
        "#SpawnItem <itemName> <amount> <extras>",
        "#SpawnItem2 <search text>",
        "#SpawnRandomAnimal <amount>",
        "#SpawnRandomZombie <amount>",
        "#SpawnRazor <SteamID64|coordinates>",
        "#SpawnVehicle <vehicle> <amount> <extras>",
        "#SpawnZombie <puppet> <amount> <location>",
        "#SquadInfo <steamID>",
        "#StartTournamentMode <centerX> <centerY> <delay> <duration>",
        "#Teleport <X> <Y> <Z> <name|SteamID64>",
        "#TeleportTo <name|SteamID64>",
        "#TeleportTo3pm <name|SteamID64>",
        "#TeleportToMe <name|SteamID64>",
        "#TeleportToVehicle <vehicleID>",
        "#ToggleAmbientSound",
        "#ToggleFog",
        "#Unban <SteamID64>",
        "#Unmute <name|SteamID64>",
        "#Unsilence <name|SteamID64>",
        "#Vote <event>",
        "#VisualizeBulletTrajectories true",
        "#VisualizePath start <xyz> end <xyz>",
        "#VisualizePlayerAiming true",
        "#VisualizeVehicleTrajectory true"
    }.OrderBy(command => command, StringComparer.OrdinalIgnoreCase).ToArray();
}
